# This is a basic workflow to help you get started with Actions

name: Pull Fixtures

on:
  schedule:
    - cron:  '0 10 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: install npm packages
        run: |
          npm install

      - name: execute pull-fixtures script # run main.py
        run: |
          node pull-fixtures.mjs
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add fixtures.json
          git commit -m "[Cron] Updating Fixture List"
          git push
